# Generated by Django 6.0.6 on 2026-06-13 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('completed', 'Completed'), ('partial', 'Partially Imported'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('raw_csv_content', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_reports', to='groups.group')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='CSV row number (1-indexed, including header)')),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Entry'), ('missing_field', 'Missing Required Field'), ('format_error', 'Format Error'), ('math_error', 'Mathematical Error'), ('name_mismatch', 'Name Mismatch/Variant'), ('date_error', 'Date Format Error'), ('negative_amount', 'Negative Amount'), ('zero_amount', 'Zero Amount'), ('membership_violation', 'Membership Violation'), ('misclassification', 'Misclassified Entry'), ('conflicting_data', 'Conflicting Data'), ('rounding', 'Rounding Issue'), ('currency_missing', 'Missing Currency'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('field_name', models.CharField(blank=True, default='', help_text='The CSV column where the anomaly was found', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the problem')),
                ('original_value', models.TextField(blank=True, default='', help_text='The original value from the CSV')),
                ('suggested_value', models.TextField(blank=True, default='', help_text='The suggested corrected value')),
                ('suggested_action', models.TextField(blank=True, default='', help_text='Description of the suggested resolution')),
                ('resolution', models.CharField(choices=[('pending', 'Pending Review'), ('auto_fixed', 'Auto-Fixed'), ('user_approved', 'User Approved'), ('user_modified', 'User Modified'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('resolved_value', models.TextField(blank=True, default='', help_text='The final value after user review')),
                ('user_notes', models.TextField(blank=True, default='', help_text='Notes added by user during review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('import_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='importer.importreport')),
            ],
            options={
                'verbose_name_plural': 'Import anomalies',
                'ordering': ['row_number', 'created_at'],
            },
        ),
    ]
